language: python

python:
  - "2.7"

install:
  - pip install -e .

jobs:
  include:
    - stage: pep8
      before_script: pip install pep8
      script: pep8 --show-pep8 --max-line-length=100 sms4you

    - stage: pylint
      before_script: pip install pylint
      script: pylint --disable=C,R sms4you
